shellEmulator: true

trustPolicy: no-downgrade

packages: []
catalogs:
  dev:
    '@antfu/eslint-config': ^7.0.0
    '@types/ini': ^4.1.1
    '@types/node': ^24.10.8
    '@types/which': ^3.0.4
    bumpp: ^10.4.0
    eslint: ^9.39.2
    lint-staged: ^16.2.7
    simple-git-hooks: ^2.13.1
    taze: ^19.9.2
    tsx: ^4.21.0
    typescript: ^5.9.3
    unbuild: ^3.6.1
    vitest: ^4.0.17
  prod:
    ansis: ^4.2.0
    fzf: ^0.5.2
    package-manager-detector: ^1.6.0
    tinyexec: ^1.0.2
    tinyglobby: ^0.2.15
  prod-inlined:
    '@posva/prompts': ^2.4.4
    ini: ^5.0.0
    terminal-link: ^4.0.0
    which: ^5.0.0
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
