packages: []
catalogs:
  dev:
    '@antfu/eslint-config': ^6.0.0
    '@types/ini': ^4.1.1
    '@types/node': ^24.8.0
    '@types/which': ^3.0.4
    bumpp: ^10.3.1
    eslint: ^9.37.0
    lint-staged: ^16.2.4
    simple-git-hooks: ^2.13.1
    taze: ^19.7.0
    tsx: ^4.20.6
    typescript: ^5.9.3
    unbuild: ^3.6.1
    vitest: ^3.2.4
  prod:
    ansis: ^4.2.0
    fzf: ^0.5.2
    package-manager-detector: ^1.5.0
    tinyexec: ^1.0.1
    tinyglobby: ^0.2.15
  prod-inlined:
    '@posva/prompts': ^2.4.4
    ini: ^5.0.0
    terminal-link: ^4.0.0
    which: ^5.0.0
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
