packages: []
catalogs:
  dev:
    '@antfu/eslint-config': ^5.3.0
    '@types/ini': ^4.1.1
    '@types/node': ^24.5.2
    '@types/which': ^3.0.4
    bumpp: ^10.2.3
    eslint: ^9.35.0
    lint-staged: ^16.1.6
    simple-git-hooks: ^2.13.1
    taze: ^19.6.0
    tinyglobby: ^0.2.15
    tsx: ^4.20.5
    typescript: ^5.9.2
    unbuild: ^3.6.1
    vitest: ^3.2.4
  prod:
    ansis: ^4.1.0
    fzf: ^0.5.2
    package-manager-detector: ^1.3.0
    tinyexec: ^1.0.1
  prod-inlined:
    '@posva/prompts': ^2.4.4
    ini: ^5.0.0
    terminal-link: ^4.0.0
    which: ^5.0.0
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
