packages: []
catalogs:
  dev:
    '@antfu/eslint-config': ^4.13.2
    '@types/ini': ^4.1.1
    '@types/node': ^22.15.21
    '@types/which': ^3.0.4
    bumpp: ^10.1.1
    eslint: ^9.27.0
    lint-staged: ^16.0.0
    simple-git-hooks: ^2.13.0
    taze: ^19.1.0
    tinyglobby: ^0.2.14
    tsx: ^4.19.4
    typescript: ^5.8.3
    unbuild: ^3.5.0
    vitest: ^3.1.4
  prod:
    ansis: ^4.0.0
    fzf: ^0.5.2
    package-manager-detector: ^1.3.0
    tinyexec: ^1.0.1
  prod-inlined:
    '@posva/prompts': ^2.4.4
    ini: ^5.0.0
    terminal-link: ^4.0.0
    which: ^5.0.0
onlyBuiltDependencies:
  - simple-git-hooks
  - unrs-resolver
