shellEmulator: true
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 10080 # 1 week
packages: []
catalogs:
  dev:
    '@antfu/eslint-config': ^9.2.0
    '@types/ini': ^4.1.1
    '@types/node': ^26.1.2
    '@types/which': ^3.0.4
    bumpp: ^12.1.1
    eslint: ^10.8.0
    lint-staged: ^17.3.0
    simple-git-hooks: ^2.13.1
    taze: ^19.17.1
    tsdown: ^0.22.14
    tsx: ^4.23.6
    typescript: ^6.0.3
    vitest: ^4.1.10
  prod:
    fzf: ^0.5.2
    package-manager-detector: ^1.8.0
    tinyexec: ^1.3.0
    tinyglobby: ^0.2.17
  prod-inlined:
    '@posva/prompts': ^2.4.4
    fast-npm-meta: ^2.2.0
    ini: ^7.0.0
    pnpm-workspace-yaml: ^1.7.0
    which: ^7.0.0
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
allowBuilds:
  esbuild: true
  simple-git-hooks: true
update:
  ignoreDeps:
    - typescript@7
